require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/embedded_contents", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EmbeddedContent. As you add validations to EmbeddedContent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      EmbeddedContent.create! valid_attributes
      get embedded_contents_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      embedded_content = EmbeddedContent.create! valid_attributes
      get embedded_content_url(embedded_content)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_embedded_content_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      embedded_content = EmbeddedContent.create! valid_attributes
      get edit_embedded_content_url(embedded_content)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EmbeddedContent" do
        expect {
          post embedded_contents_url, params: { embedded_content: valid_attributes }
        }.to change(EmbeddedContent, :count).by(1)
      end

      it "redirects to the created embedded_content" do
        post embedded_contents_url, params: { embedded_content: valid_attributes }
        expect(response).to redirect_to(embedded_content_url(EmbeddedContent.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EmbeddedContent" do
        expect {
          post embedded_contents_url, params: { embedded_content: invalid_attributes }
        }.to change(EmbeddedContent, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post embedded_contents_url, params: { embedded_content: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested embedded_content" do
        embedded_content = EmbeddedContent.create! valid_attributes
        patch embedded_content_url(embedded_content), params: { embedded_content: new_attributes }
        embedded_content.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the embedded_content" do
        embedded_content = EmbeddedContent.create! valid_attributes
        patch embedded_content_url(embedded_content), params: { embedded_content: new_attributes }
        embedded_content.reload
        expect(response).to redirect_to(embedded_content_url(embedded_content))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        embedded_content = EmbeddedContent.create! valid_attributes
        patch embedded_content_url(embedded_content), params: { embedded_content: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested embedded_content" do
      embedded_content = EmbeddedContent.create! valid_attributes
      expect {
        delete embedded_content_url(embedded_content)
      }.to change(EmbeddedContent, :count).by(-1)
    end

    it "redirects to the embedded_contents list" do
      embedded_content = EmbeddedContent.create! valid_attributes
      delete embedded_content_url(embedded_content)
      expect(response).to redirect_to(embedded_contents_url)
    end
  end
end
