require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/stage_schedules", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # StageSchedule. As you add validations to StageSchedule, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      StageSchedule.create! valid_attributes
      get stage_schedules_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      stage_schedule = StageSchedule.create! valid_attributes
      get stage_schedule_url(stage_schedule)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_stage_schedule_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      stage_schedule = StageSchedule.create! valid_attributes
      get edit_stage_schedule_url(stage_schedule)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StageSchedule" do
        expect {
          post stage_schedules_url, params: { stage_schedule: valid_attributes }
        }.to change(StageSchedule, :count).by(1)
      end

      it "redirects to the created stage_schedule" do
        post stage_schedules_url, params: { stage_schedule: valid_attributes }
        expect(response).to redirect_to(stage_schedule_url(StageSchedule.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StageSchedule" do
        expect {
          post stage_schedules_url, params: { stage_schedule: invalid_attributes }
        }.to change(StageSchedule, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post stage_schedules_url, params: { stage_schedule: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested stage_schedule" do
        stage_schedule = StageSchedule.create! valid_attributes
        patch stage_schedule_url(stage_schedule), params: { stage_schedule: new_attributes }
        stage_schedule.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the stage_schedule" do
        stage_schedule = StageSchedule.create! valid_attributes
        patch stage_schedule_url(stage_schedule), params: { stage_schedule: new_attributes }
        stage_schedule.reload
        expect(response).to redirect_to(stage_schedule_url(stage_schedule))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        stage_schedule = StageSchedule.create! valid_attributes
        patch stage_schedule_url(stage_schedule), params: { stage_schedule: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested stage_schedule" do
      stage_schedule = StageSchedule.create! valid_attributes
      expect {
        delete stage_schedule_url(stage_schedule)
      }.to change(StageSchedule, :count).by(-1)
    end

    it "redirects to the stage_schedules list" do
      stage_schedule = StageSchedule.create! valid_attributes
      delete stage_schedule_url(stage_schedule)
      expect(response).to redirect_to(stage_schedules_url)
    end
  end
end
